# Generated by Django 3.1.7 on 2021-03-14 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays', '0007_auto_20210310_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('images', models.ImageField(default='', upload_to='home/pro_image')),
                ('description', models.TextField()),
                ('createdat', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_on', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc))),
                ('comment', models.TextField()),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.blogs')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderforpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('passengers', models.IntegerField(default=0)),
                ('daya_tour', models.IntegerField(default=0)),
                ('date_tour', models.DateTimeField()),
                ('enddate_tour', models.DateTimeField()),
                ('order_status', models.CharField(default='', max_length=50)),
                ('date_ordered', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 22, 21, 23, 844313)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 51, 23, 844313, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='orderforpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.packages'),
        ),
    ]
