# Generated by Django 3.1.7 on 2021-03-15 09:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays', '0009_auto_20210315_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='', upload_to='holidays/pro_image'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 14, 31, 19, 598602)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_image',
            field=models.ImageField(default='', upload_to='holidays/pro_image'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderforpackage',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 597555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_video',
            field=models.FileField(default='', upload_to='holidays/pro_image'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 1, 19, 598602, tzinfo=utc))),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default='', max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderforpackage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.order'),
        ),
    ]
