# Generated by Django 3.1.7 on 2021-03-15 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0013_auto_20210315_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 778744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 779735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 15, 31, 38, 770402)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 770402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 770402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderforpackage',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 770402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 770402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_images',
            field=models.ImageField(default='', upload_to='holidays/package_image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_video',
            field=models.FileField(default='', upload_to='holidays/package_videos'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 770402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 10, 1, 38, 777709, tzinfo=utc)),
        ),
    ]
