# Generated by Django 3.1.7 on 2021-04-01 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0034_auto_20210401_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affialiate_click',
            old_name='date_visited',
            new_name='date_logged_in',
        ),
        migrations.RemoveField(
            model_name='affialiate_click',
            name='date_loged_in',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 21, 16, 32, 825440)),
        ),
    ]
