# Generated by Django 3.1.7 on 2021-05-02 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0064_auto_20210430_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='routines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(blank=True, default='', max_length=200)),
                ('day2', models.CharField(blank=True, default='', max_length=200)),
                ('day3', models.CharField(blank=True, default='', max_length=200)),
                ('day4', models.CharField(blank=True, default='', max_length=200)),
                ('day5', models.CharField(blank=True, default='', max_length=200)),
                ('day6', models.CharField(blank=True, default='', max_length=200)),
                ('day7', models.CharField(blank=True, default='', max_length=200)),
                ('day8', models.CharField(blank=True, default='', max_length=200)),
                ('day9', models.CharField(blank=True, default='', max_length=200)),
                ('day_10', models.CharField(blank=True, default='', max_length=200)),
                ('day_11', models.CharField(blank=True, default='', max_length=200)),
                ('day_12', models.CharField(blank=True, default='', max_length=200)),
                ('day_13', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='affiliate_info_user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliate_success',
            name='date_affiliate_successfull',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliate_transaction',
            name='date_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliateaccounts',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliateinfo',
            name='date_edited',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='banner',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 525671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='timecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 22, 16, 47, 509788)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderforpackage',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 526717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 46, 47, 509788, tzinfo=utc)),
        ),
    ]
