# Generated by Django 3.1.7 on 2021-05-03 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0069_auto_20210503_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate_info_user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliate_success',
            name='date_affiliate_successfull',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliate_transaction',
            name='date_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliateaccounts',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='affiliateinfo',
            name='date_edited',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='banner',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='timecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 22, 28, 13, 803841)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderforpackage',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 802846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day9',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day_10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day_11',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day_12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routines',
            name='day_13',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 16, 58, 13, 803841, tzinfo=utc)),
        ),
    ]
